name: 'time_parser_tool'
description: |
  根据用户输入的时间字符串，解析并返回开始和结束日期。
  
  工具输入参数说明：
    - input: 用户输入的时间字符串（如："上个月"、"本月"、"最近一周"等）
  
  工具返回格式：
    {
      "start_date": "YYYY-MM-DD",
      "end_date": "YYYY-MM-DD"
    }
  
  调用示例：
    Action Input: {"input": "上个月"}
    返回: {"start_date": "2025-11-01", "end_date": "2025-11-30"}
input_keys: ['input']
metadata:
  type: 'TOOL'
  module: 'backend.infrastructure.intelligence.agentic.tool.time_parser_tool'
  class: 'TimeParserTool'